'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DotNetChess.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1305376984_ark2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305376984_ark2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305376984_ark21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305376984_ark21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305377080_Download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305377080_Download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305377129_Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305377129_Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305377221_download_box_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305377221_download_box_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305377308_folder_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305377308_folder_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305377359_mail_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305377359_mail-new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305377528_Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305377528_Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305377603_gtk_media_forward_ltr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305377603_gtk-media-forward-ltr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305378012_gtk_go_back_ltr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305378012_gtk-go-back-ltr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305378016_gtk_go_back_rtl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305378016_gtk-go-back-rtl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305378204_gtk_media_forward_ltr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305378204_gtk-media-forward-ltr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305378342_Gnome_Go_Previous_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305378342_Gnome-Go-Previous-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305378363_Gnome_Go_Last_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305378363_Gnome-Go-Last-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305378382_Gnome_Go_First_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305378382_Gnome-Go-First-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305378539_gtk_go_back_rtl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305378539_gtk-go-back-rtl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305378928_kalarm_disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305378928_kalarm_disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1305379035_start_here_gnome_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1305379035_start-here-gnome-green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3d_chess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3d-chess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aboutO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aboutO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aboutus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aboutus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Audio_Cd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Audio_Cd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BISHOP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BISHOP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exitO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exitO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property index() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property load() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loadO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Q() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Q", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property white_queen_2d_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("white_queen_2d-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WhiteBishop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhiteBishop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WhiteKnight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhiteKnight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WhiteQueen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhiteQueen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WhiteRook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhiteRook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
